version: '3.3'

volumes:
  foodgram_db:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./backend/foodgram/.env
    volumes:
      - foodgram_db:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: ./backend/foodgram/.env
    volumes:
      - static:/backend_static
      - media:/app/media/images
    depends_on:
      - db
  frontend:
    build: ./frontend/
    volumes:
      - static:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media/images
    depends_on:
      - frontend
      - backend
      - db
